package exception;

public class ExceptionEx1 {

	public static void main(String[] args) 
		{
			try
			{
				
			int i;
			return;
		}
catch (Exception e)
{
	System.out.println ("inside catch block");
	}
finally
		
	{
	System.out.println("inside finally block");	
	}
}}