package exception;

public class Exception4 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
int num1,num2;
try
{
	num1=0;
	num2=62/num1;
	System.out.println("Try block massage");
}
catch ( ArithmeticException e)
{
	System.out.println("Error: don't devide a numbur by zero");
}
	}
	{
 System.out.println("i'am out of try-catch block java") ;
	}
} 
	 
	 
	









	


